services:
  django:
    build:
      context: ./code-back
      dockerfile: Dockerfile
    container_name: django_app
    restart: always
    volumes:
      - ./code-back:/code-back
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: db
      DB_USER: postgres
      DB_PASSWORD: 12345
      DB_HOST: db
      DB_PORT: 5432

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5435:5435"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
